---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  labels:
    k8s-app: traefik-ingress-lb
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - port: 80
      name: http
    # - port: 8080
    #   name: http-alt
    - port: 443
      name: https
    # - port: 8443
    #   name: https-alt
  externalIPs:
    - 192.168.1.150
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-webui
  labels:
    k8s-app: traefik-ingress-lb
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - port: 8088
      name: webui
  externalIPs:
    - 192.168.1.150
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
data:
  traefik.toml: |
    # traefik.toml
    defaultEntryPoints = ["http"]
    #defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      #[entryPoints.http.redirect]
      #entryPoint = "https"
      #[entryPoints.http.auth.basic]
      #users = ["will:HASH"]
      #[entryPoints.https.auth.basic]
      #users = ["will:HASH"]
      #[entryPoints.https]
      #address = ":443"
      #[entryPoints.https.tls]
    #[acme]
    #email = "will@moggridge.com"
    #storageFile = "/acme/acme.json"
    #entryPoint = "https"
    #onDemand = true
    #onHostRule = true
    #caServer = "https://acme-staging.api.letsencrypt.org/directory"
    #[[acme.domains]]
    #main = "wgm.io"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: traefik-ingress-controller
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config
          configMap:
            name: traefik-conf
        - name: acme
          hostPath:
            path: /srv/configs/acme
      containers:
        - image: containous/traefik
          name: traefik-ingress-lb
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
          volumeMounts:
            - mountPath: "/config"
              name: "config"
            - mountPath: "/acme"
              name: "acme"
          ports:
            - containerPort: 80
              # hostPort: 80
            - containerPort: 443
              # hostPort: 443
            - containerPort: 8080
              # hostPort: 8088
          args:
            - --configfile=/config/traefik.toml
            - --web
            - --kubernetes
            - --logLevel=DEBUG
