apiVersion: v1
kind: Service
metadata:
  name: plex
  labels:
    app: plex
spec:
  selector:
    app: plex
  ports:
    - name: plex
      port: 32400
      targetPort: 32400
  type: NodePort
  externalIPs:
    - 192.168.1.150
