---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: homeassistant
  labels:
    app: homeassistant
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: homeassistant.will.lan
      http:
        paths:
          - backend:
              serviceName: homeassistant
              servicePort: 80
