---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: homeassistant
  labels:
    app: homeassistant
  annotations:
    kubernetes.io/ingress.class: "traefik"
    # ingress.kubernetes.io/whitelist-source-range: "127.0.0.1/32, 192.168.0.0/17"
spec:
  rules:
    - host: homeassistant.will.lan
      http:
        paths:
          - backend:
              serviceName: homeassistant
              servicePort: 80
