kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: appdaemon
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: appdaemon
    spec:
      containers:
      - name: appdaemon
        image: acockburn/appdaemon
        imagePullPolicy: Always
        ports:
        - containerPort: 5050
          name: dashboard
        env:
        - name: HA_URL
          value: "http://homeassistant"
        # - name: HA_KEY
        #   value: ""
        - name: DASH_URL
          value: "http://0.0.0.0:5050"
          # value: "http://$HOSTNAME:5050"
        volumeMounts:
        - name: appdaemon-config
          mountPath: /conf
        - name: localtime
          mountPath: /etc/localtime
      volumes:
      - name: appdaemon-config
        nfs:
          server: 192.168.1.128
          path: /volume1/configs/appdaemon
      - name: localtime
        hostPath:
          path: /etc/localtime